pipeline_name: dijkstra

# --- train ---
batch_size: 32
learning_rate: 0.0003
weight_decay: 0.0
num_iterations: 500
eval_each: 500
stepwise_training: true
use_hints: true
hint_loss_weight: false
processor_lower_t: 0.5
processor_upper_t: 3.
states_lower_t: 0.01
states_upper_t: 3.
use_noise: true

# --- data ---
weighted_graphs: true
generate_random_numbers: false
generate_start: true

sampler_name:
  train: er
  val: er
  test: er

samples_count:
  train: 1000
  val: 256
  test: 256

problem_size:
  train: 16
  val: 17
  test: 160

# --- model ---
h: 128
use_discrete_bottleneck: true
node_states_count: 2
edge_states_count: 3
message_top_one_choice: global
position_dim: -1
steps_mul: 1
output_location: edge
update_scalars: true
temp_on_eval: 0.

# --- logs, io ---
models_directory: models
tensorboard_logs: true